/**
 *
 * @param Theme can be spread like {Colors, NavigationColors, Gutters, Layout, Common, ...args}
 * @return {*}
 */
export default function () {
  return {
    logo: require('@/Assets/Images/logo.png'),
    logo_full: require('@/Assets/Images/logo_full.png'),
    logo_blue: require('@/Assets/Images/logo_blue.png'),
    notification_empty: require('@/Assets/Images/Notification-Empty.png'),
    home: require('@/Assets/Images/home.png'),
    left_arrow: require('@/Assets/Images/left_arrow.png'),
    orders_default: require('@/Assets/Images/Orders_default.png'),
    reward: require('@/Assets/Images/reward.png'),
    orders_active: require('@/Assets/Images/Orders_active.png'),
    facebook: require('@/Assets/Images/facebook.png'),
    Email: require('@/Assets/Images/Email.png'),
    LastTag: require('@/Assets/Images/lastTag.png'),
    Copylink: require('@/Assets/Images/Copylink.png'),
    SMS: require('@/Assets/Images/SMS.png'),
    Whatsapp: require('@/Assets/Images/Whatsapp.png'),
    Twitter: require('@/Assets/Images/Twitter.png'),
    pricing_default: require('@/Assets/Images/Pricing_default.png'),
    pricing_active: require('@/Assets/Images/Pricing_active.png'),
    question_default: require('@/Assets/Images/Question_default.png'),
    question_active: require('@/Assets/Images/Question_active.png'),
    account_default: require('@/Assets/Images/Account_default.png'),
    account_active: require('@/Assets/Images/Account_active.png'),
    order_background: require('@/Assets/Images/order_background.png'),
    best_value: require('@/Assets/Images/best_value.png'),
    right_blue_arrow: require('@/Assets/Images/right_blue_arrow.png'),
    checked: require('@/Assets/Images/checked.png'),
    close: require('@/Assets/Images/close.png'),
    howItWorks1: require('@/Assets/Images/how_it_works1.png'),
    howItWorks2: require('@/Assets/Images/how_it_works2.png'),
    howItWorks3: require('@/Assets/Images/how_it_works3.png'),
    remove: require('@/Assets/Images/remove.png'),
    add: require('@/Assets/Images/add.png'),
    apple_pay: require('@/Assets/Images/apple-pay.png'),
    info: require('@/Assets/Images/Info.png'),
    success: require('@/Assets/Images/success.png'),
    camera: require('@/Assets/Images/Camera.png'),
    instructionBackground: require('@/Assets/Images/instruction_back.png'),
    freshieTest: require('@/Assets/Images/test.png'),
    wallet: require('@/Assets/Images/Wallet.png'),
    wallet_active: require('@/Assets/Images/Wallet_active.png'),
    ambrose: require('@/Assets/Images/ambrose.png'),
    rating: require('@/Assets/Images/Ratings.png'),
    pin: require('@/Assets/Images/pin.png'),
    white_check: require('@/Assets/Images/white_check.png'),
  }
}
